config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  resources :categories
  resources :comments
  resources :ratings
  resources :places
  resources :users
  resources :welcomes

  get 'welcome/index'
  root 'welcome#index'
  #facebook sign in
  # get 'auth/:provider/:callback', to: "sessions#create"
  #facebook logout
  # get 'signout', to: "sessions#destroy", as: sign_out

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/places' => 'welcome#index'
  post '/places/:id/rate' => 'places#rate'
  
  post '/get_users_id' => 'users#get_users_id'
  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  post '/ratings' => 'ratings#create', :as => 'rate'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'

end




  

app/models/rating.rb
class Rating < ActiveRecord::Base
has_and_belongs_to_many :users
belongs_to :place
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @rating = Rating.create
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show

  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create

   if request.xhr? #ajax request
    @rating = Rating.find_or_create_by(rating: params[:rating].to_i, place_id: params[:place_id], user_id: current_user.id)
      render :nothing => true, :status => 201 
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
  end

 
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:rating, [:id, :rating])
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<div class="row">
  <div class="small-2 large-2 columns">
    <%= imdb_style_rating_for @movie, current_user%>
  </div>
  <br>
  <div class="small-2 large-4 columns">
    <% if current_user %>
      Atmospher: <%= rating_for @movie, "visual_effects" %>
      <br>
      Drinks: <%= rating_for @movie, "original_score" %>
      <br>
      Wait Time: <%= rating_for @movie, "original_score" %>
      <br>
      Cost: <%= rating_for @movie, "custome_design" %>
      <br>
      Music: <%= rating_for @movie, "custome_design" %>
    <% end %>
  </div>
</div>