config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  resources :categories
  resources :comments
  resources :ratings
  resources :places
  resources :users
  resources :welcomes

  get 'welcome/index'
  root 'welcome#index'
  #facebook sign in
  # get 'auth/:provider/:callback', to: "sessions#create"
  #facebook logout
  # get 'signout', to: "sessions#destroy", as: sign_out

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/places' => 'welcome#index'
  post '/places/:id/rate' => 'places#rate'
  
  post '/get_users_id' => 'users#get_users_id'
  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  post '/ratings' => 'ratings#create', :as => 'rate'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'

end




  

app/models/place.rb
class Place < ApplicationRecord
	# include Geocoder
	has_many :ratings
  has_many :comment
  validates :yelp_id, uniqueness: true
 #  reverse_geocoded_by :latitude => :coordinate_latitude, :longitude => :coordinate_longitude, :address => :geo_address
	# after_validation :reverse_geocode  # auto-fetch address
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  include YelpTools
  # GET /places
  # GET /places.json
  def index
     profile=YelpTools.search('33127', yelp_parameters("Nightlife", 40))
     @image_urls=[]
     
     profile.businesses.each do |biz|
        biz.image_url
        found_place=Place.find_or_create_by(name: biz.name, address: biz.location.address.flatten.join, phone: biz.phone, city: biz.location.city, state_code: biz.location.state_code, postal_code: biz.location.postal_code, neighborhoods: get_neighborhood(biz), coordinate_latitude: biz.location.coordinate.latitude, coordinate_longitude: biz.location.coordinate.longitude, yelp_id: biz.id, image_url: biz.image_url)
        # found_place.image_url=biz.image_url
        @image_urls << biz.image_url
    end

    @places = Place.all
    
    unless session[:user_id]
      @places=Place.first 3
      @image_urls=@image_urls.slice 0,3
    end
  end

  def self.saved_places

  end


  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    @coordinate_latitude = @place.coordinate_latitude.to_f
    gon.coordinateLatitude = @coordinate_latitude
    @coordinate_longitude =  @place.coordinate_longitude.to_f
    gon.coordinateLongitude = @coordinate_longitude
    @place_name =  @place.name
    gon.placeName = @place_name
    @place_address =  @place.address
    gon.placeAddress = @place_address
    @place_phone = @place.phone
    gon.placePhone = @place_phone
    @place_city = @place.city
    gon.placeCity = @place_city
    @place_state =  @place.state_code
    gon.placeState = @place_state
    @place_postal = @place.postal_code
    gon.placePostal = @place_postal
    @rating = Rating.new
  end
  
    # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json

  def create
    @place = Place.new(place_params)
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :phone)
    end
    def yelp_parameters(terms,limits)
      { term: terms, limit: limits}
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
    <%= link_to 'Edit', edit_place_path(place) %> |
    <%= link_to 'Back', places_path %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.yelp_id %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: 'layouts/loc' %>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
  <div class="table-responsive">
    <table class="table">
      <tbody>
        <td><h2><strong><%= @place.name %></strong></h2></td>
        <tr>
          <td><strong>Address:</strong></td>
          <td><%= @place.address %><br>
          <%= @place.city %> <%= @place.state_code %> <%= @place.postal_code %></td>
        </tr>
        <tr>
          <td><strong>Neighborhood:</strong></td>
          <td><%= @place.neighborhoods %></td>
        </tr>
          <td><strong>Phone:</strong></td>
          <td><%= @place.phone %></td>
      </tbody>
    </table>
  </div>
  <%= render partial: 'layouts/gmap' %>

    <br>
    <%= render partial: 'layouts/raters' %>
  </div>
  <br>
  <br>
  <br>
      