config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  resources :categories
  resources :comments
  resources :ratings
  resources :places
  resources :users
  resources :welcomes

  get 'welcome/index'
  root 'welcome#index'
  #facebook sign in
  # get 'auth/:provider/:callback', to: "sessions#create"
  #facebook logout
  # get 'signout', to: "sessions#destroy", as: sign_out

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/places' => 'welcome#index'
  post '/places/:id/rate' => 'places#rate'
  
  post '/get_users_id' => 'users#get_users_id'
  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  post '/ratings' => 'ratings#create', :as => 'rate'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'

end




  

app/views/layouts/_foot.html.erb
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Register', '/signup' %>
<% end %>

app/views/layouts/_form.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "LIT", root_path,{ :class=>"navbar-brand"} %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"></li>
      </ul>
        <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="City or Zip">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </div>
      </form>
        <li><%= link_to "My Profile", current_user%></li>
        <li><%= link_to "Logout", logout_path, method: "destroy" %></li>
        <% else %>
        <li><%= link_to " Register", signup_path, { :class=>"glyphicon glyphicon-user"} %></li>
        <li><%= link_to " Login", login_path, { :class=>"glyphicon glyphicon-user"} %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_gmap.html.erb
<div id="map"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["JS_KEY"] %>&libraries=places&callback=initMap" async defer></script>

app/views/layouts/_iframe.html.erb
<div id="accordion">
	<div class="map-responsive">
		<iframe
		id="map-selective"
		width="300"
	  height="300"
	  frameborder="0" style="border:0"
		src="https://www.google.com/maps/embed/v1/view?key=AIzaSyAlgF4bIl8uLIqhycYl1cMrpUxftD082Cw&center=<%= @place.coordinate_latitude.to_f.round(4)%>,<%= @place.coordinate_longitude.to_f.round(4) %>&zoom=18&maptype=roadmap" allowfullscreen>
		</iframe>
	</div>
</div>

app/views/layouts/_loc.html.erb
<dl>
<% if @profile %>
    <% @profile.businesses.each do |biz| %>
    
    <dd>
    <h1><%= link_to biz.name, places_path %></a></h1><br>
    <img src="<%= biz.image_url %>"><br>
    <%= biz.location.address.join %><br>
    <%= biz.location.city %>, <%= biz.location.state_code %> <%= biz.location.postal_code %> <br>
    <% if biz.location.neighborhoods %>
    Neighborhood: <%= biz.location.neighborhoods.join %><br>
    <% end %>
    <%= biz.location.coordinate.latitude %>
    <%= biz.location.coordinate.longitude %><br>
    Phone:<%= biz.display_phone %><br>
    <hr>

  <% end %>
        <% else %>
    no places yo
<% end %>

  
</dl>

app/views/layouts/_navbar.html.erb
  <div class="navbar-fixed">
    <nav role="navigation">
      <div class="nav-wrapper container">
        <%= link_to "lit", root_path,{ :class=>"brand-logo", :id=>'logo-container'} %>
          <% if current_user %>
        <li><a class="dropdown-button" href='#!' data-activates='dropdown1'>Menu<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><%= link_to "My Profile", current_user%></li>
          <li><%= link_to "Logout", logout_path, method: "destroy" %></li>
          <% else %>
          <li><%= link_to " Register", signup_path, { :class=>"glyphicon glyphicon-user"} %></li>
          <li><%= link_to " Login", login_path, { :class=>"glyphicon glyphicon-user"} %></li>
        <ul class="right hide-on-med-and-down">
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Menu<i class="material-icons right">arrow_drop_down</i></a></li>
          <% end %>
        </ul>
        <ul id="nav-mobile" class="side-nav">
          <li><%= link_to "lit", root_path,{ :class=>"brand-logo", :id=>'logo-container'} %></li>
                <% if current_user %>
          <li><%= link_to "My Profile", current_user%></li>
          <li><%= link_to "Logout", logout_path, method: "destroy" %></li>
          <% else %>
          <li><%= link_to " Register", signup_path, { :class=>"glyphicon glyphicon-user"} %></li>
          <li><%= link_to " Login", login_path, { :class=>"glyphicon glyphicon-user"} %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

      

app/views/layouts/_raters.html.erb
<div class="ratings-container">
    <div id="ratingdiv">
      <!--Here put a hidden field with the business id so you can pass it in the ajax post -->
      <!-- I hard coded it here. Define it in controller and use erb tag to print it in-->
      <input id="place" type="hidden" value="<%= @place.id %>">

      <!-- These can be defined in the controller -->
      <% fire_off_path = 'fire-off1.png' %>
      <% ids = ['one', 'two', 'three', 'four', 'five'] %>
      <% ids.each do |img_id| %>      
      <div><img src="<%= image_path(fire_off_path) %>" class="undone" id="<%= img_id %>" ></div>
        <% end %>
    </div>
    <script type="text/JavaScript">

      $(document).ready(function (){
         var user_id = 'user_id': $.ajax({
                          type: "POST",
                          url: "/get_users_id"
                          }).done(function() {
                          console.log(current_user)
                          console.log('current_user')
                        });
          console.log("hello")
         $('#ratingdiv .undone').on("click", function(e){
           e.preventDefault();
           var bigStar = '<%= image_path('big-star.png') %>',
               flameOut = '<%= image_path('fire-off1.png') %>';
           var lookup = {
             'one': 1,
             'two': 2,
             'three': 3,
             'four': 4,
             'five': 5
           },
           lookupId = {
             1: $('#one'),
             2: $('#two'),
             3: $('#three'),
             4: $('#four'),
             5: $('#five')
           },
           toggle = {};
           toggle[bigStar] = flameOut;
           toggle[flameOut] = bigStar;
           
          var place_id = $('#place').val();
          var clickedElementId = $(this).attr('id'),
              number = lookup[clickedElementId],
              rating = {
                'rating': number, 
                'place_id': place_id
              };
              
          console.log(rating);
          // submit to server
          $.post('/ratings', rating)
          // toggle the first one
          if ( number === 1 ){
            var src = $(this).attr('src');
            var newSrc = toggle[src];
            $(this).attr('src', toggle[src]);
            if (newSrc === flameOut){
              // set rating to nil
              $.post('/ratings', {'rating': null} )
               for (i=2; i <=5; i++){
                lookupId[i].attr('src', flameOut);
               }
            }
          };
          for (var i=2; i <= number; i++){
            if ( i === 2 ) {
              lookupId[1].attr('src', bigStar);
            };
            var clickedElement = lookupId[i];
            $(clickedElement).attr('src', bigStar);
            for(var n=i+1; n <= 5; n++){
              var unClickElement = lookupId[n];
              $(unClickElement).attr('src', flameOut);
            }
          }
         });
      });

    </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Lit2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="//maps.google.com/maps/api/js?key=AIzaSyAlgF4bIl8uLIqhycYl1cMrpUxftD082Cw"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <%= Gon::Base.render_data %>
  </head>
<body>
	<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</body>
</html>